const { v4: uuidv4 } = require('uuid')

export const products = [
	{
		id: uuidv4(),
		title: 'Apple iPhone 13',
		desc: 'The latest flagship smartphone from Apple',
		image:
			'https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-13-finish-select-202207-6-1inch-midnight?wid=2560&hei=1440&fmt=jpeg&qlt=95&.v=1656712887881',
		price: 1299,
		type: 'mobile phone',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Samsung Galaxy S21',
		desc: 'Powerful Android smartphone with a stunning display',
		image: 'https://mobile-city.pl/pol_pm_Samsung-Galaxy-S21-5G-G991-8-128GB-Dual-Sim-Fioletowy-33399_1.jpg',
		price: 999,
		type: 'mobile phone',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Google Pixel 6',
		desc: 'High-end smartphone with a top-notch camera',
		image: 'pixel6.jpg',
		price: 899,
		type: 'mobile phone',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'OnePlus 9 Pro',
		desc: 'Flagship smartphone with fast performance and impressive display',
		image: 'oneplus9pro.jpg',
		price: 899,
		type: 'mobile phone',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Xiaomi Mi 11',
		desc: 'Affordable smartphone with powerful hardware',
		image: 'mi11.jpg',
		price: 699,
		type: 'mobile phone',
		category: 'sale',
	},
	{
		id: uuidv4(),
		title: 'Sony Xperia 1 III',
		desc: 'Premium smartphone with a 4K OLED display and advanced camera system',
		image: 'xperia1iii.jpg',
		price: 1199,
		type: 'mobile phone',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Samsung Galaxy Note 20 Ultra',
		desc: 'Feature-packed smartphone with S Pen support',
		image: 'galaxyNote20Ultra.jpg',
		price: 1099,
		type: 'mobile phone',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'iPhone SE (2022)',
		desc: 'Compact and powerful iPhone with an affordable price',
		image: 'iphoneSE2022.jpg',
		price: 599,
		type: 'mobile phone',
		category: 'sale',
	},
	{
		id: uuidv4(),
		title: 'OnePlus Nord 2',
		desc: 'Mid-range smartphone with impressive performance',
		image: 'oneplusNord2.jpg',
		price: 399,
		type: 'mobile phone',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Xiaomi Redmi Note 10 Pro',
		desc: 'Budget-friendly smartphone with a high-resolution camera',
		image: 'redmiNote10Pro.jpg',
		price: 299,
		type: 'mobile phone',
		category: 'sale',
	},
	{
		id: uuidv4(),
		title: 'Apple Watch Series 7',
		desc: 'The latest smartwatch from Apple with advanced features',
		image: 'appleWatchSeries7.jpg',
		price: 399,
		type: 'smartwatch',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Samsung Galaxy Watch 4',
		desc: 'High-end smartwatch with fitness tracking capabilities',
		image: 'galaxyWatch4.jpg',
		price: 349,
		type: 'smartwatch',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Fitbit Versa 3',
		desc: 'Versatile smartwatch with built-in GPS and health monitoring',
		image: 'fitbitVersa3.jpg',
		price: 229,
		type: 'smartwatch',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Garmin Fenix 6 Pro',
		desc: 'Premium multisport smartwatch with rugged design',
		image: 'garminFenix6Pro.jpg',
		price: 599,
		type: 'smartwatch',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Amazfit GTS 2',
		desc: 'Affordable smartwatch with AMOLED display and long battery life',
		image: 'amazfitGTS2.jpg',
		price: 129,
		type: 'smartwatch',
		category: 'sale',
	},
	{
		id: uuidv4(),
		title: 'Huawei Watch GT 2 Pro',
		desc: 'Stylish smartwatch with exceptional battery life',
		image: 'huaweiWatchGT2Pro.jpg',
		price: 249,
		type: 'smartwatch',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Fossil Gen 5',
		desc: 'Fashionable smartwatch with Wear OS by Google',
		image: 'fossilGen5.jpg',
		price: 199,
		type: 'smartwatch',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Xiaomi Mi Watch Lite',
		desc: 'Affordable smartwatch with basic fitness tracking features',
		image: 'miWatchLite.jpg',
		price: 79,
		type: 'smartwatch',
		category: 'sale',
	},
	{
		id: uuidv4(),
		title: 'TicWatch Pro 3',
		desc: 'Advanced smartwatch with dual-display technology',
		image: 'ticWatchPro3.jpg',
		price: 299,
		type: 'smartwatch',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Garmin Venu 2',
		desc: 'Smartwatch with vibrant AMOLED display and health monitoring',
		image: 'garminVenu2.jpg',
		price: 349,
		type: 'smartwatch',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Samsung Galaxy Watch Active 2',
		desc: 'Sleek and lightweight smartwatch with fitness tracking',
		image: 'galaxyWatchActive2.jpg',
		price: 249,
		type: 'smartwatch',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Amazfit Bip U Pro',
		desc: 'Budget-friendly smartwatch with built-in GPS and heart rate monitoring',
		image: 'amazfitBipUPro.jpg',
		price: 69,
		type: 'smartwatch',
		category: 'sale',
	},
	{
		id: uuidv4(),
		title: 'Huawei Watch Fit',
		desc: 'Lightweight and stylish smartwatch with long battery life',
		image: 'huaweiWatchFit.jpg',
		price: 99,
		type: 'smartwatch',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Fitbit Sense',
		desc: 'Advanced health and fitness smartwatch with stress management features',
		image: 'fitbitSense.jpg',
		price: 299,
		type: 'smartwatch',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Garmin Forerunner 245 Music',
		desc: 'GPS running smartwatch with music storage and playback',
		image: 'garminForerunner245Music.jpg',
		price: 299,
		type: 'smartwatch',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Sony WH-1000XM4',
		desc: 'High-quality wireless noise-cancelling headphones',
		image: 'sonyWH1000XM4.jpg',
		price: 349,
		type: 'headphones',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Bose QuietComfort 35 II',
		desc: 'Comfortable over-ear headphones with excellent noise cancellation',
		image: 'boseQuietComfort35II.jpg',
		price: 299,
		type: 'headphones',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Apple AirPods Pro',
		desc: 'Wireless earbuds with active noise cancellation',
		image: 'appleAirPodsPro.jpg',
		price: 249,
		type: 'headphones',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Sennheiser HD 660 S',
		desc: 'Open-back headphones for audiophiles',
		image: 'sennheiserHD660S.jpg',
		price: 499,
		type: 'headphones',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Jabra Elite 85t',
		desc: 'True wireless earbuds with advanced sound quality',
		image: 'jabraElite85t.jpg',
		price: 229,
		type: 'headphones',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Beyerdynamic DT 990 Pro',
		desc: 'Professional open-back studio headphones',
		image: 'beyerdynamicDT990Pro.jpg',
		price: 199,
		type: 'headphones',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'JBL Free X',
		desc: 'True wireless earbuds with a compact design',
		image: 'jblFreeX.jpg',
		price: 99,
		type: 'headphones',
		category: 'sale',
	},
	{
		id: uuidv4(),
		title: 'Audio-Technica ATH-M50x',
		desc: 'Popular closed-back headphones for studio and DJ use',
		image: 'audioTechnicaATHM50x.jpg',
		price: 149,
		type: 'headphones',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Sennheiser Momentum True Wireless 2',
		desc: 'Premium true wireless earbuds with excellent sound quality',
		image: 'sennheiserMomentumTrueWireless2.jpg',
		price: 299,
		type: 'headphones',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Sony WF-1000XM4',
		desc: 'Wireless earbuds with industry-leading noise cancellation',
		image: 'sonyWF1000XM4.jpg',
		price: 279,
		type: 'headphones',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Beats Studio3 Wireless',
		desc: 'Stylish over-ear headphones with balanced sound',
		image: 'beatsStudio3Wireless.jpg',
		price: 349,
		type: 'headphones',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'JBL Live 650BTNC',
		desc: 'Wireless headphones with active noise cancellation',
		image: 'jblLive650BTNC.jpg',
		price: 199,
		type: 'headphones',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Bose SoundSport Free',
		desc: 'True wireless earbuds designed for sports activities',
		image: 'boseSoundSportFree.jpg',
		price: 179,
		type: 'headphones',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'AKG K371',
		desc: 'Closed-back studio headphones with accurate sound reproduction',
		image: 'akgK371.jpg',
		price: 149,
		type: 'headphones',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Jabra Elite 75t',
		desc: 'Compact true wireless earbuds with great call quality',
		image: 'jabraElite75t.jpg',
		price: 179,
		type: 'headphones',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Apple iPad Pro',
		desc: 'Powerful tablet with a stunning display and advanced features',
		image: 'ipadPro.jpg',
		price: 999,
		type: 'tablets',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Samsung Galaxy Tab S7+',
		desc: 'High-end Android tablet with a large AMOLED display',
		image: 'galaxyTabS7Plus.jpg',
		price: 849,
		type: 'tablets',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Microsoft Surface Pro 7',
		desc: 'Versatile 2-in-1 tablet with a detachable keyboard',
		image: 'surfacePro7.jpg',
		price: 899,
		type: 'tablets',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Amazon Fire HD 10',
		desc: 'Affordable tablet with a Full HD display and Alexa integration',
		image: 'fireHD10.jpg',
		price: 149,
		type: 'tablets',
		category: 'sale',
	},
	{
		id: uuidv4(),
		title: 'Lenovo Tab P11 Pro',
		desc: 'Premium Android tablet with a vibrant OLED display',
		image: 'tabP11Pro.jpg',
		price: 499,
		type: 'tablets',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Huawei MatePad Pro',
		desc: 'Sleek and powerful tablet with a large screen and fast performance',
		image: 'matePadPro.jpg',
		price: 699,
		type: 'tablets',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Apple MacBook Pro',
		desc: 'Powerful laptop with stunning Retina display and long battery life',
		image: 'macbookPro.jpg',
		price: 1999,
		type: 'laptop',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Dell XPS 15',
		desc: 'Premium laptop with a sleek design and excellent performance',
		image: 'dellXPS15.jpg',
		price: 1799,
		type: 'laptop',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'HP Spectre x360',
		desc: 'Versatile 2-in-1 laptop with a convertible design and high-quality display',
		image: 'hpSpectreX360.jpg',
		price: 1399,
		type: 'laptop',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Lenovo ThinkPad X1 Carbon',
		desc: 'Lightweight and durable business laptop with powerful performance',
		image: 'thinkpadX1Carbon.jpg',
		price: 1499,
		type: 'laptop',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Asus ROG Zephyrus G14',
		desc: 'Gaming laptop with a powerful AMD processor and high-refresh-rate display',
		image: 'rogZephyrusG14.jpg',
		price: 1599,
		type: 'laptop',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Microsoft Surface Laptop 4',
		desc: 'Slim and stylish laptop with excellent build quality and smooth performance',
		image: 'surfaceLaptop4.jpg',
		price: 1299,
		type: 'laptop',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Acer Predator Helios 300',
		desc: 'Gaming laptop with powerful specifications and a high-refresh-rate display',
		image: 'predatorHelios300.jpg',
		price: 1199,
		type: 'laptop',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Razer Blade 15',
		desc: 'Sleek gaming laptop with a high-refresh-rate display and customizable RGB keyboard',
		image: 'razerBlade15.jpg',
		price: 1899,
		type: 'laptop',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'LG Gram 14',
		desc: 'Ultra-lightweight laptop with long battery life and a durable build',
		image: 'lgGram14.jpg',
		price: 999,
		type: 'laptop',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Lenovo Yoga C940',
		desc: 'Flexible 2-in-1 laptop with a high-resolution display and powerful performance',
		image: 'yogaC940.jpg',
		price: 1299,
		type: 'laptop',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Alienware M15 R4',
		desc: 'High-performance gaming laptop with a futuristic design and advanced features',
		image: 'alienwareM15R4.jpg',
		price: 2199,
		type: 'laptop',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'HP Envy 13',
		desc: 'Stylish and portable laptop with a vibrant display and fast performance',
		image: 'hpEnvy13.jpg',
		price: 1099,
		type: 'laptop',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Asus ZenBook 14',
		desc: 'Slim and lightweight laptop with a powerful processor and immersive display',
		image: 'zenbook14.jpg',
		price: 1299,
		type: 'laptop',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Microsoft Surface Book 3',
		desc: 'Premium 2-in-1 laptop with detachable display and excellent performance',
		image: 'surfaceBook3.jpg',
		price: 1799,
		type: 'laptop',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Acer Swift 3',
		desc: 'Affordable and lightweight laptop with a long battery life and decent performance',
		image: 'acerSwift3.jpg',
		price: 699,
		type: 'laptop',
		category: 'sale',
	},
	{
		id: uuidv4(),
		title: 'Lenovo Legion 5',
		desc: 'Gaming laptop with powerful specifications and a high-refresh-rate display',
		image: 'legion5.jpg',
		price: 1299,
		type: 'laptop',
		category: 'regular',
	},
]
