const { v4: uuidv4 } = require('uuid')

export const productsList = [
	{
		id: uuidv4(),
		title: 'Apple iPhone 13',
		desc: 'The latest flagship smartphone from Apple',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/32/3225298/APPLE_iPhone_13__front_czarny.jpg',
		price: 1299,
		type: 'mobile phone',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Samsung Galaxy S21',
		desc: 'Powerful Android smartphone with a stunning display',
		image: 'https://mobile-city.pl/pol_pm_Samsung-Galaxy-S21-5G-G991-8-128GB-Dual-Sim-Fioletowy-33399_1.jpg',
		price: 999,
		type: 'mobile phone',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Google Pixel 6',
		desc: 'High-end smartphone with a top-notch camera',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/42/4204568/Smartfon-GOOGLE-Pixel-6a-6-128GB-5G-6-1-Zielony-front-tyl.jpg',
		price: 899,
		type: 'mobile phone',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'OnePlus 9 Pro',
		desc: 'Flagship smartphone with fast performance and impressive display',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/29/2915234/Etui-SPIGEN-Liquid-Air-do-OnePlus-9-Pro-Czarny-front.jpg',
		price: 899,
		type: 'mobile phone',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Xiaomi Mi 11',
		desc: 'Affordable smartphone with powerful hardware',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/29/2960614/Smartfon-XIAOMI-Mi-11-Lite-5G-Zolty-tyl-front__1.jpg',
		price: 699,
		type: 'mobile phone',
		category: 'sale',
	},
	{
		id: uuidv4(),
		title: 'Sony Xperia 1 III',
		desc: 'Premium smartphone with a 4K OLED display and advanced camera system',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/30/3049852/Smartfon-SONY-Xperia-1-III-5G-Czarny-tyl-front.jpg',
		price: 1199,
		type: 'mobile phone',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Samsung Galaxy Note 20 Ultra',
		desc: 'Feature-packed smartphone with S Pen support',
		image: 'https://files.refurbed.com/ii/samsung-glxy-note-20-ultra-1676298739.jpg?t=resize&h=600&w=800',
		price: 1099,
		type: 'mobile phone',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'iPhone SE (2022)',
		desc: 'Compact and powerful iPhone with an affordable price',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/36/3640925/Smartfon-APPLE-iPhone-SE-2022-5G-Polnoc-1.jpg',
		price: 599,
		type: 'mobile phone',
		category: 'sale',
	},
	{
		id: uuidv4(),
		title: 'OnePlus Nord 2',
		desc: 'Mid-range smartphone with impressive performance',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/37/3760422/Smartfon-ONEPLUS-Nord-CE-2-Lite-Czarny-front-tyl.jpg',
		price: 399,
		type: 'mobile phone',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Xiaomi Redmi Note 11 Pro 5G',
		desc: 'Budget-friendly smartphone with a high-resolution camera',
		image: 'https://files.refurbed.com/ii/xiaomi-redmi-note-11-pro-5g-1676615255.jpg?t=resize&h=600&w=800',
		price: 299,
		type: 'mobile phone',
		category: 'sale',
	},
	{
		id: uuidv4(),
		title: 'Apple Watch Series 7',
		desc: 'The latest smartwatch from Apple with advanced features',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/32/3269370/Apple-Watch-Series-7-Aluminium-Polnoc.jpg',
		price: 399,
		type: 'smartwatch',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Samsung Galaxy Watch 4',
		desc: 'High-end smartwatch with fitness tracking capabilities',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/30/3084038/Smartwatch-SAMSUNG-Galaxy-Watch-4-Classic-SM-R890NZKAEUE-46mm-Czarny-skos1.jpg',
		price: 349,
		type: 'smartwatch',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Fitbit Versa 3',
		desc: 'Versatile smartwatch with built-in GPS and health monitoring',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_290_300/thumbnails/images/25/2571561/Smartwatch-FITBIT-Versa-3-Czarny-skos.jpg',
		price: 229,
		type: 'smartwatch',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Garmin Fenix 6 Pro',
		desc: 'Premium multisport smartwatch with rugged design',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/20/2003273/Zegarek-sportowy-GARMIN-Fenix-6X-Pro-Czarny-front-skos.jpg',
		price: 599,
		type: 'smartwatch',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Amazfit GTS 2',
		desc: 'Affordable smartwatch with AMOLED display and long battery life',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/26/2685829/Smartwatch-AMAZFIT-GTS-2-Czarny-front.jpg',
		price: 129,
		type: 'smartwatch',
		category: 'sale',
	},
	{
		id: uuidv4(),
		title: 'Huawei Watch GT 2 Pro',
		desc: 'Stylish smartwatch with exceptional battery life',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/25/2506402/Smartwatch-HUAWEI-Watch-GT-2-Pro-Czarny-skos-lewy-0.jpg',
		price: 249,
		type: 'smartwatch',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Fossil Gen 5',
		desc: 'Fashionable smartwatch with Wear OS by Google',
		image: 'https://image.ceneostatic.pl/data/products/85434019/f-fossil-gen-5-czarny-ftw4025.jpg',
		price: 199,
		type: 'smartwatch',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Xiaomi Mi Watch Lite',
		desc: 'Affordable smartwatch with basic fitness tracking features',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/35/3536705/Smartwatch-XIAOMI-Redmi-Watch-2-Lite-Czarny-front.jpg',
		price: 79,
		type: 'smartwatch',
		category: 'sale',
	},
	{
		id: uuidv4(),
		title: 'TicWatch Pro 3',
		desc: 'Advanced smartwatch with dual-display technology',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/36/3609785/Smartwatch-TICWATCH-Pro-3-Ultra-GPS-Czarny-skos.jpg',
		price: 299,
		type: 'smartwatch',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Garmin Venu 2',
		desc: 'Smartwatch with vibrant AMOLED display and health monitoring',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/29/2963626/Zegarek-sportowy-GARMIN-Venu-2-45mm-Czarny-front.jpg',
		price: 349,
		type: 'smartwatch',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Samsung Galaxy Watch Active 2',
		desc: 'Sleek and lightweight smartwatch with fitness tracking',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/19/1989939/Smartwatch-SAMSUNG-Galaxy-Watch-Active-2-SM-R820N-44mm-Aluminium-Czarny-01__1_.jpg',
		price: 249,
		type: 'smartwatch',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Amazfit Bip U Pro',
		desc: 'Budget-friendly smartwatch with built-in GPS and heart rate monitoring',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/38/3898002/Smartwatch-AMAZFIT-Bip-3-Pro-Czarny-skos.jpg',
		price: 69,
		type: 'smartwatch',
		category: 'sale',
	},
	{
		id: uuidv4(),
		title: 'Huawei Watch Fit',
		desc: 'Lightweight and stylish smartwatch with long battery life',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/37/3792106/Smartwatch-HUAWEI-Watch-Fit-2-Active-Czarny-skos2.jpg',
		price: 99,
		type: 'smartwatch',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Fitbit Sense',
		desc: 'Advanced health and fitness smartwatch with stress management features',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/25/2571401/Smartwatch-FITBIT-Sense-Czarny-front-skos.jpg',
		price: 299,
		type: 'smartwatch',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Garmin Forerunner 245 Music',
		desc: 'GPS running smartwatch with music storage and playback',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/38/3836074/Zegarek-sportowy-GARMIN-Forerunner-245-Music-010-02120-30-Czarny-Front1-01.jpg',
		price: 299,
		type: 'smartwatch',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Sony WH-1000XM4',
		desc: 'High-quality wireless noise-cancelling headphones',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/23/2329178/Sluchawki-nauszne-SONY-WH-1000XM4B-Czarny-skos-1.jpg',
		price: 349,
		type: 'headphones',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Bose QuietComfort 35 II',
		desc: 'Comfortable over-ear headphones with excellent noise cancellation',
		image: 'https://prod-api.mediaexpert.pl/api/images/gallery/thumbnails/images/12/1220649/1.jpg',
		price: 299,
		type: 'headphones',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Apple AirPods Pro',
		desc: 'Wireless earbuds with active noise cancellation',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/41/4118594/Sluchawki-douszne-APPLE-AirPods-Pro-II-Bialy-01.JPG',
		price: 249,
		type: 'headphones',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Sennheiser HD 660 S',
		desc: 'Open-back headphones for audiophiles',
		image: 'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/11/1176853/11.JPG',
		price: 499,
		type: 'headphones',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Jabra Elite 85t',
		desc: 'True wireless earbuds with advanced sound quality',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/29/2987110/Sluchawki-dokanalowe-JABRA-Elite-85T-ANC-Czarny-Produkt1.jpg',
		price: 229,
		type: 'headphones',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Beyerdynamic DT 990 Pro',
		desc: 'Professional open-back studio headphones',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/11/1162359/S__uchawki_BEYERDYNAMIC_DT990_PRO.jpg',
		price: 199,
		type: 'headphones',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'JBL Free X',
		desc: 'True wireless earbuds with a compact design',
		image: 'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/16/1650037/FREE_X_1.jpg',
		price: 99,
		type: 'headphones',
		category: 'sale',
	},
	{
		id: uuidv4(),
		title: 'Audio-Technica ATH-M50x',
		desc: 'Popular closed-back headphones for studio and DJ use',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/52/5285094/Sluchawki-nauszne-AUDIO-TECHNICA-ATH-M50XSTS-USB-Czarny-front-bok.jpg',
		price: 149,
		type: 'headphones',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Sennheiser Momentum True Wireless 2',
		desc: 'Premium true wireless earbuds with excellent sound quality',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery/thumbnails/images/24/2475958/Sluchawki-dokanalowe-SENNHEISER-Momentum-TWS-2-Czarny-skos.jpg',
		price: 299,
		type: 'headphones',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Sony WF-1000XM4',
		desc: 'Wireless earbuds with industry-leading noise cancellation',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/29/2972970/Sluchawki-dokanalowe-SONY-WF-1000XM4-Czarny-front.jpg',
		price: 279,
		type: 'headphones',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Beats Studio3 Wireless',
		desc: 'Stylish over-ear headphones with balanced sound',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/23/2334846/Sluchawki-nauszne-APPLE-Beats-Studio3-Czarny-front-1.jpg',
		price: 349,
		type: 'headphones',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'JBL Live 650BTNC',
		desc: 'Wireless headphones with active noise cancellation',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/18/1890043/JBL_LIVE650BTNC_Produc_Black.jpg',
		price: 199,
		type: 'headphones',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Bose SoundSport Free',
		desc: 'True wireless earbuds designed for sports activities',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/32/3210008/Sluchawki-nauszne-BOSE-QuietComfort-45-ANC-Czarny-skos.jpg',
		price: 179,
		type: 'headphones',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'AKG K371',
		desc: 'Closed-back studio headphones with accurate sound reproduction',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/20/2005549/Sluchawki-nauszne-AKG-K371-Czarny-lewy-skos.jpg',
		price: 149,
		type: 'headphones',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Jabra Elite 75t',
		desc: 'Compact true wireless earbuds with great call quality',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/21/2133949/Sluchawki-dokanalowe-JABRA-Elite-75t-Czarny-etui1.jpg',
		price: 179,
		type: 'headphones',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Apple iPad Pro',
		desc: 'Powerful tablet with a stunning display and advanced features',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/42/4234796/Tablet-APPLE-iPad-Pro-11-4-gen-Gwiezdna-szarosc-1.jpg',
		price: 999,
		type: 'tablets',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Samsung Galaxy Tab S7+',
		desc: 'High-end Android tablet with a large AMOLED display',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/30/3037048/Tablet-SAMSUNG-Galaxy-Tab-S7-FE-Czarny-front.jpg',
		price: 849,
		type: 'tablets',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Microsoft Surface Pro 7',
		desc: 'Versatile 2-in-1 tablet with a detachable keyboard',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery/thumbnails/images/25/2543402/Laptop-MICROSOFT-Surface-Pro-7-skos-prawy.jpeg',
		price: 899,
		type: 'tablets',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Amazon Fire HD 10',
		desc: 'Affordable tablet with a Full HD display and Alexa integration',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/31/3133352/Amazon-Echo-Show-10-3gen-Czarny-skos.jpg',
		price: 149,
		type: 'tablets',
		category: 'sale',
	},
	{
		id: uuidv4(),
		title: 'Lenovo Tab P11 Pro',
		desc: 'Premium Android tablet with a vibrant OLED display',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_290_300/thumbnails/images/53/5348730/Tablet-LENOVO-Tab-P11-Pro-front.jpg',
		price: 499,
		type: 'tablets',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Huawei MatePad Pro',
		desc: 'Sleek and powerful tablet with a large screen and fast performance',
		image: 'https://files.refurbed.com/ii/huawei-matepad-pro-10-8-1642080935.jpg?t=resize&h=600&w=800',
		price: 699,
		type: 'tablets',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Apple MacBook Pro',
		desc: 'Powerful laptop with stunning Retina display and long battery life',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/51/5134110/Laptop-APPLE-MacBook-Pro-2023-1.jpg',
		price: 1999,
		type: 'laptop',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Dell XPS 15',
		desc: 'Premium laptop with a sleek design and excellent performance',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/42/4242316/Laptop-DELL-XPS-9315-9218-skos-lewy__1.jpg',
		price: 1799,
		type: 'laptop',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'HP Spectre x360',
		desc: 'Versatile 2-in-1 laptop with a convertible design and high-quality display',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/43/4390052/Laptop-HP-Spectre-x360-16-f1139nw-front.jpg',
		price: 1399,
		type: 'laptop',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Lenovo ThinkPad X1 Carbon',
		desc: 'Lightweight and durable business laptop with powerful performance',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/37/3772518/Laptop-LENOVO-ThinkPad-X1-Yoga-Gen-7-front.jpg',
		price: 1499,
		type: 'laptop',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Asus ROG Zephyrus G14',
		desc: 'Gaming laptop with a powerful AMD processor and high-refresh-rate display',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/51/5141146/Laptop-ASUS-ROG-Zephyrus-G14-GA402NV-N2007W-przod.jpg',
		price: 1599,
		type: 'laptop',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Microsoft Surface Laptop 4',
		desc: 'Slim and stylish laptop with excellent build quality and smooth performance',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/37/3746290/Laptop-MICROSOFT-Surface-Laptop-4-02.jpg',
		price: 1299,
		type: 'laptop',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Acer Predator Helios 300',
		desc: 'Gaming laptop with powerful specifications and a high-refresh-rate display',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/42/4204944/Laptop-3D-ACER-Predator-Helios-300-PH315-55S-SpatialLabs-2.jpg',
		price: 1199,
		type: 'laptop',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Razer Blade 15',
		desc: 'Sleek gaming laptop with a high-refresh-rate display and customizable RGB keyboard',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/35/3584077/Laptop-RAZER-Blade-15-Advanced-15.6-240Hz-i7-12800H-16GB-SSD-1TB-GeForce-RTX3060-Windows-11-Home-front.jpg',
		price: 1899,
		type: 'laptop',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'LG Gram 14',
		desc: 'Ultra-lightweight laptop with long battery life and a durable build',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/38/3832462/Laptop-LG-Gram-14Z90Q-G.AA78Y-przod.jpg',
		price: 999,
		type: 'laptop',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Lenovo Yoga C940',
		desc: 'Flexible 2-in-1 laptop with a high-resolution display and powerful performance',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/42/4247440/Laptop-LENOVO-Yoga-Slim-7-Pro-14IAH7-przod.jpg',
		price: 1299,
		type: 'laptop',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Alienware M15 R4',
		desc: 'High-performance gaming laptop with a futuristic design and advanced features',
		image: 'https://cdn.x-kom.pl/i/setup/images/prod/big/product-new-big,,2023/3/pr_2023_3_3_9_17_19_352_02.jpg',
		price: 2199,
		type: 'laptop',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'HP Envy 13',
		desc: 'Stylish and portable laptop with a vibrant display and fast performance',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/37/3797290/Laptop-DELL-Alienware-m15-R7-przod-1.jpg',
		price: 1099,
		type: 'laptop',
		category: 'regular',
	},
	{
		id: uuidv4(),
		title: 'Asus ZenBook 14',
		desc: 'Slim and lightweight laptop with a powerful processor and immersive display',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/52/5216542/Laptop-ASUS-ZenBook-Flip-UP3404VA-1.jpg',
		price: 1299,
		type: 'laptop',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Microsoft Surface Book 3',
		desc: 'Premium 2-in-1 laptop with detachable display and excellent performance',
		image:
			'https://f00.esfr.pl/foto/2/65674149761/83d6cc13508bbdfc795c05f5cdad833b/microsoft-laptop-book-3-i5-8gb-256ssd-w10,65674149761_3.jpg',
		price: 1799,
		type: 'laptop',
		category: 'newest',
	},
	{
		id: uuidv4(),
		title: 'Acer Swift 3',
		desc: 'Affordable and lightweight laptop with a long battery life and decent performance',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/39/3944550/Laptop-ACER-Swift-3-SF314-71-14-OLED-00-2.jpg',
		price: 699,
		type: 'laptop',
		category: 'sale',
	},
	{
		id: uuidv4(),
		title: 'Lenovo Legion 5',
		desc: 'Gaming laptop with powerful specifications and a high-refresh-rate display',
		image:
			'https://prod-api.mediaexpert.pl/api/images/gallery_500_500/thumbnails/images/43/4333884/Laptop-LENOVO-Legion-5-15ITH6-front.jpg',
		price: 1299,
		type: 'laptop',
		category: 'regular',
	},
]
